server:
  port: 9010

spring:
  application:
    name: springkafka-explorer
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  kafka:
#    bootstrap-servers: localhost:9092
    producer:
#      key-serializer: org.apache.kafka.common.serialization.LongSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic:
        default: qs-topic
        user-creation: user-creation
      acks: all
      retries: 3
    consumer:
      group-id:
        default: qs-topic-consumer
        user-creation: user-creation
#      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
#      properties:
#        spring.json:
#          trusted.packages: com.nigam.springkafkaexplorer.*



