server:
  port: 9010

spring:
  application:
    name: springkafka-explorer
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic:
        default: ide-quickstart-events
    consumer:
      group-id:
        default: quickstart-event-consumer



